// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaLYdroy_ckuZtCIKSEs7v3cXx6O_LW9A',
    appId: '1:81741681254:android:2b9b981e3d75e05942d3a7',
    messagingSenderId: '81741681254',
    projectId: 'qrgenration',
    storageBucket: 'qrgenration.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFiMOvOAYNnqYvVA8ECHK6tSJ5UPYofA8',
    appId: '1:81741681254:ios:57ff9fa995a42aff42d3a7',
    messagingSenderId: '81741681254',
    projectId: 'qrgenration',
    storageBucket: 'qrgenration.firebasestorage.app',
    androidClientId: '81741681254-4q8o264be3osso6ge1o33rbpdp05d7e4.apps.googleusercontent.com',
    iosClientId: '81741681254-1u7pum31sqd4tq6vf0djiotmhvvc9tt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrGenration',
  );
}
